name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.x'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build App
        run: npm run build:backend

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t achi596/openspaces-backend:latest .
          docker tag achi596/openspaces-backend:latest achi596/openspaces-backend:${{ github.sha }}
      - name: Push Docker image
        run: |
          docker push achi596/openspaces-backend:latest
          docker push achi596/openspaces-backend:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t achi596/openspaces-frontend:latest -f Frontend/Dockerfile Frontend
          docker tag achi596/openspaces-frontend:latest achi596/openspaces-frontend:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push achi596/openspaces-frontend:latest
          docker push achi596/openspaces-frontend:${{ github.sha }}